@host=http://localhost:5268
@adminId=3fa85f64-5717-4562-b3fc-2c963f66afa6

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free", // "Starter", "Pro"
    "AdminId": "{{adminId}}"
}

#{
#    "Id": "{{adminId}}"
#    "SubscriptionType": "Free", // "Starter", "Pro"
#}