@host=http://localhost:5268
@adminId=2150e333-8fdc-9474-1a3956d46de8

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free", // "Starter", "Pro"
    "AdminId": "{{adminId}}"
}

#{
#    "Id": "{{adminId}}"
#    "SubscriptionType": "Free", // "Starter", "Pro"
#}